### ISSUE TITLE
[Bug] Missing "Open in new tab", works in Chrome

### ISSUE THREAD

**Issue by aluo-x** [uazo/bromite-buildtools#214] opened 2023-05-21 15:37 UTC
Description:
In bromite, long pressing a link only has the "Open in new tab in group", there is no option to "Open in new tab".
In chrome you get both options.

Expected behavior:
Bromite long press has "Open in new tab" option

Version:
113.0.5672.127 and 113.0.5672.63

**Comment by bocekm** [comment] 2023-05-22 12:25
Duplicate of https://github.com/uazo/bromite-buildtools/issues/172.

**Closed** 2023-05-23 06:54 UTC
