### ISSUE TITLE
Enhancement idea

### ISSUE THREAD

**Issue by ViktorKahu** [uazo/bromite-buildtools#185] opened 2023-05-07 13:34 UTC
Talking about the android version of Chromite here.

Not sure how hard it would be to implement or if there are fundamental ideological reasons against it...

It would be really nice to have a homescreen (new tab default page) with all the favourites (bookmarks) in it. Not just frequently visited sights, but actual bookmarks.

And here's the thing - it would be nice to have it in always incognito mode also, instead of the black screen with incognito mode info. Sure, this info is important first time, but not every time, every day. Also, this info does not need to take up the entire screen.

It would be nice to have this screen persist through automatic sight data clearing also. No cookies need to be involved, only an address - a quick link to a saved website. I don't think that implementing this would bare any security or privacy risks.

At the moment, the bookmarks are counter-intuitive and not user-friendly, it's almost quicker to type the address in the address bar than navigate through the menus to find it.

An example of such a homescreen done right can be seen in samsung browser non-incognito mode.

PS: I believe that samsung browser is also based on Chromium, and since they have partially implemented it (not in incognito mode), it's definitely possible.

**Comment by ViktorKahu** [comment] 2023-05-07 14:15
You are 1/4 of the way there already as something similar is already implemented in non-incognito mode.

Except the tiles are not bookmarks, they are frequently visited sites - hence they disappear with clearing of browser data.

I think they need to be replaced with bookmarks.

And in incognito mode, the tiles could just display the first letter of the url instead of site logos.

**Comment by uazo** [comment] 2023-05-07 14:25
duplicate of https://github.com/uazo/cromite/issues/323

**Closed by uazo** 2023-05-07 14:25 UTC
