### ISSUE TITLE
Unable to download from the website tinywow.com

### ISSUE THREAD

**Issue by marinoalfonz1** [uazo/bromite-buildtools#195] opened 2023-05-12 08:24 UTC
Unable to download files from the website tinywow.com . It is saying download failed bad certificate.

Version 113.0.5672.63

<details><summary>Details</summary>
<p>

![Screenshot_20230512-135303_Chromium](https://github.com/uazo/bromite-buildtools/assets/85938685/b1400f18-7d2e-43b7-b335-013aa4144826)

</p>
</details>

**Comment by uazo** [comment] 2023-05-12 08:41
duplicate of https://github.com/uazo/bromite-buildtools/issues/192

**Closed by uazo** 2023-05-12 08:41 UTC
