### ISSUE TITLE
Downloads fail because of 'Bad Certificate'

### ISSUE THREAD

**Issue by cy4njk** [uazo/bromite-buildtools#206] opened 2023-05-17 14:19 UTC
Pretty much the title of the issue: on both the windows and android versions whenever I want to download anything the download fails because of a 'bad certificate'. 

I am using the newest version from the releases tab on both my android and windows devices.

**Comment by uazo** [comment] 2023-05-19 06:47
duplicate of https://github.com/uazo/bromite-buildtools/issues/192

**Closed by uazo** 2023-05-19 06:47 UTC
