### ISSUE TITLE
Can't open 9gag.com normally

### ISSUE THREAD

**Issue by privacyonly** [uazo/bromite-buildtools#207] opened 2023-05-18 02:32 UTC
I cleared bromite data just in case

https://9gag.com
"This site can't be reached" "ERR_FAILED"

am I blocked? No

https://9gag.com/tag/r
now it loads, I just need to press the back arrow at the top left of the page and here we go 
https://9gag.com

Bromite 113.0.5672.63
Android 13 One UI 5.1
Samsung S21 Ultra 
Android Security Patch level may 1, 2023

**Comment by eskimododo** [comment] 2023-05-18 08:55
Temp workaround would be to disable internal firewall via chrome flags.. I alerted uazo on this issue as well..

**Comment by uazo** [comment] 2023-05-19 06:49
duplicate of https://github.com/uazo/cromite/issues/335

please use search before opening new issues

**Closed by uazo** 2023-05-19 06:49 UTC
