### ISSUE TITLE
Internal firewall block renderer_initiated_download

### ISSUE THREAD

**Issue by ViktorKahu** [uazo/bromite-buildtools#192] opened 2023-05-10 07:03 UTC
Already for the 3rd time, when downloading a .apk file via the browser, the download starts and does not continue, just sits as a 0 kb file in my downloads folder.

It's 100% browser-related because it happened from at least 2 different respected websites that have nothing to do with each other. When downloaded the same .apk files via vanadium, they downloaded correctly.

Furthermore, there is no possible way to delete/rename/move the 0 kb files from downloads (tried everything in the book, short of a factory reset) even after clearing all app data/cache from chromium and deleting Chromium itself.

Now I'm stuck with three 0kb .apk files that I can't get rid of.

**Comment by uazo** [comment] 2023-05-10 07:46
ok, Let's try to figure it out.
use `chrome://net-export`, reproduce the bug and submit the log

**Comment by ViktorKahu** [comment] 2023-05-10 07:48
Thanks, will try a little bit later tonight when I get home.

**Comment by ViktorKahu** [comment] 2023-05-10 08:17
I have a log.json file, I don't know how to upload it here - there doesn't seem to be an option.

Any ideas?

**Comment by ViktorKahu** [comment] 2023-05-11 01:35
I wasn't able to upload the log without using a computer. Here is a [Link](https://www.udrop.com/88pj/chrome-net-export-log.json) to a file hosting sitr where I left the log.

Now, I don't know how to get rid of these :(

![Screenshot_20230510-175430~2](https://github.com/uazo/bromite-buildtools/assets/125934998/ae3ff4fe-20df-4408-8441-627ac7dc5155)

**Comment by uazo** [comment] 2023-05-11 07:06
thanks for the help. it is because of the [firewall](https://github.com/uazo/cromite/issues/335), the `renderer_initiated_download` call is blocked

**Comment by uazo** [comment] 2023-05-11 07:11
> Now, I don't know how to get rid of these :(

try to clear application storage

**Comment by uazo** [comment] 2023-05-20 07:38
fixed in https://github.com/uazo/bromite/commit/58909944b8fdaf5e76a3ce98d6193644db5ccda4

**Closed by uazo** 2023-05-20 07:38 UTC
Labels: wip
